version: "3.4"

services:
  genos-bank-zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: genos.bank.zookeeper
    container_name: genos.bank.zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - genos-bank-network

  genos-bank-kafka:
    image: confluentinc/cp-kafka:7.0.1
    hostname: genos.bank.kafka
    container_name: genos.bank.kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'genos.bank.zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://genos.bank.kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - 9092:9092
    networks:
      - genos-bank-network
  
  genos-bank-mongo:
    image: mongo:5.0.11
    restart: always
    hostname: genos.bank.mongo
    container_name: genos.bank.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - genos-bank-network

  genos-bank-mysql:
    image: mysql:5.7.34
    hostname: genos.bank.mysql
    container_name: genos.bank.mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - genos-bank-network

networks:
  genos-bank-network:
    name: genos-bank-network
    driver: bridge
