server:
    port: 5002
    servlet:
        context-path: /api

spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: genos_bank
            username: root
            password: root
            authentication-database: admin
    kafka:
        producer:
            bootstrap-servers: localhost:9092
